import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return(

    <html lang="en">
      <body>
        <header style={{ display: 'flex', justifyContent: 'center', padding: '1rem', background: '#282727' }}>
          <h1 className="text-2xl font-bold">
            My TEST task app
          </h1>
        </header>

        <main
          className={`${geistSans.variable} ${geistMono.variable} font-sans flex flex-col items-center justify-center min-h-screen p-8 gap-16`}
        >
          {children}
        </main>

        <footer style={{ display: 'flex', justifyContent: 'center', padding: '1rem', background: '#282727'}}>
          <p>© 2023 My Task App</p>
        </footer>


      </body>
    </html>

  )
}
